### ISSUE TITLE
Benchmarks on other silicon...

### ISSUE THREAD

**Issue by alphastrata** [fereidani/rust-channel-benchmarks#3]
Are you interested in more benchmarks from a wider variety of silicon? (Was mostly doing this to verify findings on my end.. cool crate)
`CPU: AMD Ryzen 9 5950X (32) @ 5.000GHz on  OS: Pop!_OS 21.10 x86_64`

I will try them it on my 2013 macbook later is you're interested -- I just slapped it on charge.

Plots:
![plot_bounded](https://user-images.githubusercontent.com/25101888/179185380-0adb60ea-a2c9-4340-a6c9-8da5948abe0d.png)
![plot_bounded0](https://user-images.githubusercontent.com/25101888/179185390-a35950c4-42a9-4af0-977e-385c0303ab70.png)
![plot_bounded1](https://user-images.githubusercontent.com/25101888/179185397-b9e86e00-186e-4484-86fb-26eb226f6f0f.png)
![plot_unbounded](https://user-images.githubusercontent.com/25101888/179185404-ecb9d388-4de6-47da-afeb-78030c00d0c8.png)

csvs:
[async-channel.csv](https://github.com/fereidani/rust-channel-benchmarks/files/9119250/async-channel.csv)
[crossbeam-channel.csv](https://github.com/fereidani/rust-channel-benchmarks/files/9119251/crossbeam-channel.csv)
[flume.csv](https://github.com/fereidani/rust-channel-benchmarks/files/9119253/flume.csv)
[flume_async.csv](https://github.com/fereidani/rust-channel-benchmarks/files/9119254/flume_async.csv)
[futures-channel.csv](https://github.com/fereidani/rust-channel-benchmarks/files/9119255/futures-channel.csv)
[go.csv](https://github.com/fereidani/rust-channel-benchmarks/files/9119256/go.csv)
[kanal.csv](https://github.com/fereidani/rust-channel-benchmarks/files/9119257/kanal.csv)
[kanal-async.csv](https://github.com/fereidani/rust-channel-benchmarks/files/9119258/kanal-async.csv)
[mpsc.csv](https://github.com/fereidani/rust-channel-benchmarks/files/9119259/mpsc.csv)

**Comment by fereidani** [comment]
Hi thanks for your test, i added a label to your test so others can find it easy. yes sure you can send your other results, I'll be happy to check those too.

**Comment by alphastrata** [comment]
Cool cool;
FYI
Rust: rustc 1.62.0
Go: go version go1.18.3 linux/amd64
same versions as you (forgot to add them)
