### ISSUE TITLE
Consider adding thingbuf

### ISSUE THREAD

**Issue by flxo** [fereidani/rust-channel-benchmarks#8]
The [thingbuf](https://github.com/hawkw/thingbuf) mpsc implementation is a lock-free array-based concurrent ring buffer that allows access to slots in the buffer by reference. It's also [asynchronous](https://docs.rs/thingbuf/0.1/thingbuf/mpsc/index.html) and [blocking](https://docs.rs/thingbuf/0.1/thingbuf/mpsc/blocking/index.html) bounded MPSC channels implemented using the ring buffer. 

Would be great to include this in the benchmark.

**Comment by fereidani** [comment]
Hi, I'm busy right now developing Kanal itself, you are welcome to send PR, I'll be happy to merge! If it performs well, I'll keep it in the main report.
